name: Build and Deploy

on:
  push:
    branches: ["main", deployment-test]
  pull_request:
    branches: ["main", deployment-test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install and build
        run: |
          yarn install 
          yarn build
          mkdir github-pages
          mv dist github-pages
      
      - name: Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          path: github-pages
          name: github-pages
  

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: download Artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      - name: Deploy to GitHub Pages
        id: deployment
        run: |
          ls
          yarn add gh-pages
          yarn gh-pages -d dist